//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picker.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Picker.Localization.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Tool.
        /// </summary>
        internal static string keybind_ToggleTool {
            get {
                return ResourceManager.GetString("keybind_ToggleTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyedrop any object from the map, by Elektrix and Quboid.
        /// </summary>
        internal static string mod_Description {
            get {
                return ResourceManager.GetString("mod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        internal static string options_Found {
            get {
                return ResourceManager.GetString("options_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string options_NotFound {
            get {
                return ResourceManager.GetString("options_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open picked item in menu.
        /// </summary>
        internal static string options_OpenMenu {
            get {
                return ResourceManager.GetString("options_OpenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the menu (including Find It) open \nHold Control while clicking to invert this behaviour..
        /// </summary>
        internal static string options_OpenMenu_Tooltip {
            get {
                return ResourceManager.GetString("options_OpenMenu_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Button Position.
        /// </summary>
        internal static string options_ResetButtonPosition {
            get {
                return ResourceManager.GetString("options_ResetButtonPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set ground/elevated/etc mode in Fine Road Tools.
        /// </summary>
        internal static string options_SetFRTMode {
            get {
                return ResourceManager.GetString("options_SetFRTMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If FRT is enabled, should Picker set ground/elevated/etc to match picked segment?\nHold Shift while clicking to invert this behaviour..
        /// </summary>
        internal static string options_SetFRTMode_Tooltip {
            get {
                return ResourceManager.GetString("options_SetFRTMode_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string options_Unknown {
            get {
                return ResourceManager.GetString("options_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp2.
        /// </summary>
        internal static string Tmp2 {
            get {
                return ResourceManager.GetString("Tmp2", resourceCulture);
            }
        }
    }
}
